export const initialState = {
  posts: {
    data: [
      {
        id: 'ad-1',
        title: 'Ad 1 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 40,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-2',
        title: 'Ad 2 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 80,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-3',
        title: 'Ad 3 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 75,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-4',
        title: 'Ad 4 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 60,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-5',
        title: 'Ad 5 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 230,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-6',
        title: 'Ad 6 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 270,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-7',
        title: 'Ad 7 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 20,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-8',
        title: 'Ad 8 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 510,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-9',
        title: 'Ad 9 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 340,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-10',
        title: 'Ad 10 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 240,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-11',
        title: 'Ad 11 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 140,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-12',
        title: 'Ad 12 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 45,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-13',
        title: 'Ad 13 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 404,
        author: 'sdfasdasdef12334',
      },
      {
        id: 'ad-14',
        title: 'Ad 14 title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sem pulvinar, aliquet ipsum feugiat, interdum sem. Aliquam ut elit diam. Proin viverra consectetur ligula.',
        price: 50,
        author: 'sdfasdasdef12334',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  user: {
    isLoggedIn: false,
    user: 'guest',
  },
};